twig:
    file_name_pattern: '*.twig'
    
    form_themes: [ 'bootstrap_5_layout.html.twig' ]

    default_path: '%kernel.project_dir%/templates'

    globals:
        locale: 'fr'

    # Doit être désactivé (null) pour que les templates prennent le dessus
    #exception_controller: null

when@test:
    twig:
        strict_variables: true

